# Generated by Django 5.1.7 on 2025-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_string', models.CharField(max_length=500, verbose_name='Строка подключения к 1С')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Настройки интеграции с 1С',
                'verbose_name_plural': 'Настройки интеграции с 1С',
            },
        ),
        migrations.CreateModel(
            name='SyncEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('entity_type', models.CharField(choices=[('product', 'Товар'), ('category', 'Категория'), ('manufacturer', 'Производитель'), ('order', 'Заказ'), ('user', 'Пользователь')], max_length=20, verbose_name='Тип сущности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Сущность синхронизации',
                'verbose_name_plural': 'Сущности синхронизации',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('import', 'Импорт из 1С'), ('export', 'Экспорт в 1С')], max_length=10, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('in_progress', 'В процессе')], max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Журнал синхронизации',
                'verbose_name_plural': 'Журнал синхронизации',
                'ordering': ['-start_time'],
            },
        ),
    ]
