# Generated by Django 5.1.7 on 2025-03-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_visible'),
        ('integration_1c', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_visibility', models.CharField(choices=[('visible', 'Показывать на сайте'), ('hidden', 'Скрывать с сайта'), ('prompt', 'Спрашивать при импорте')], default='prompt', help_text='Видимость новых товаров на сайте при импорте', max_length=10, verbose_name='Видимость товаров по умолчанию')),
                ('allow_price_edit', models.BooleanField(default=True, help_text='Позволяет указать цену товара при импорте', verbose_name='Разрешить редактирование цены')),
                ('allow_category_edit', models.BooleanField(default=True, help_text='Позволяет выбрать категорию товара при импорте', verbose_name='Разрешить выбор категории')),
                ('default_category', models.ForeignKey(blank=True, help_text='Если категория товара не найдена, будет использована эта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройки импорта',
                'verbose_name_plural': 'Настройки импорта',
            },
        ),
    ]
