# Generated by Django 5.1.7 on 2025-03-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_1c', '0002_importsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='Внешний ID')),
                ('data', models.TextField(help_text='Данные товара в формате JSON', verbose_name='Данные товара')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('imported', 'Импортирован'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Товар ожидающий импорта',
                'verbose_name_plural': 'Товары ожидающие импорта',
                'ordering': ['-created'],
            },
        ),
    ]
