# Generated by Django 5.1.7 on 2025-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Если отключено, товар не будет отображаться на сайте', verbose_name='Отображать на сайте'),
        ),
    ]
