# Generated by Django 5.1.7 on 2025-03-19 01:28

import DjangoProject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='До 300 символов для наилучшего отображения в поисковых системах', max_length=300, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Разделите ключевые слова запятыми', max_length=255, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название категории', max_length=150, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Используется для микроразметки Schema.org', max_length=100, verbose_name='Бренд для Schema.org'),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, help_text='Штрихкод товара для микроразметки Schema.org', max_length=14, verbose_name='GTIN/EAN/UPC код'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='До 300 символов для наилучшего отображения в поисковых системах', max_length=300, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Разделите ключевые слова запятыми', max_length=255, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название товара', max_length=150, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='mpn',
            field=models.CharField(blank=True, help_text='Код производителя для микроразметки Schema.org', max_length=50, verbose_name='MPN (код производителя)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', validators=[DjangoProject.validators.validate_file_extension, DjangoProject.validators.validate_file_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='manufacturers/', validators=[DjangoProject.validators.validate_file_extension, DjangoProject.validators.validate_file_size], verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', validators=[DjangoProject.validators.validate_file_extension, DjangoProject.validators.validate_file_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/additional/', validators=[DjangoProject.validators.validate_file_extension, DjangoProject.validators.validate_file_size], verbose_name='Изображение'),
        ),
    ]
