# Generated by Django 5.1.7 on 2025-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('business', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
    ]
